### ISSUE TITLE
Place of DTO Mapping in the stack

### ISSUE THREAD

**Issue by adkhaila** [jhipster/jhipster-sample-app-dto#1]
Hi Julien
Why DTO mapping is not done just after the service layer , and just before the controllers layer.
This would allegiate the controllers from dealing with entities , and make service layer retrun DTOs and accept DTOs 
Looking forward for your explanation
Good Work

**Comment by jdubois** [comment]
I'm sorry this is just a sample project, please ask your question on jhipster/generator-jhipster
